class Localization {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Common
      'status': 'STATUS',
      'active': 'ACTIVE',
      'remote': 'REMOTE',
      'out': 'OUT',
      'method': 'Method: ',
      'fingerprint': 'Fingerprint',
      'nfc': 'NFC',
      'manual_override': 'Manual Override',
      'logs': 'LOGS',
      'date': 'Date',
      'time': 'Time',
      'type': 'Type',
      'notes': 'Notes / Comments',
      'submit': 'SUBMIT',

      // Dashboard
      'welcome_back': 'WELCOME BACK,',
      'current_session': 'CURRENT SESSION',
      'time_matrix': 'TIME MATRIX',
      'weekly_pacing_desc': 'Weekly Pacing',
      'logged_hours': 'LOGGED HOURS',
      'shift_ends_in': 'Shift ends in',
      'session_standby': 'Session is currently STANDBY',
      'weekly_goal_pacing': 'WEEKLY GOAL PACING • وتيرة الأهداف',
      'target': 'Target:',
      'completed': 'Completed:',
      'pacing': 'Pacing',
      'weekly_presence': 'WEEKLY PRESENCE • الحضور الأسبوعي',
      'pacing_indicators': 'Pacing indicators',
      'next_engagements': 'NEXT ENGAGEMENTS • الارتباطات القادمة',
      'agenda_details': 'Agenda details & verification nodes',
      'add_event': 'ADD EVENT',
      'hr_advisory': 'COGNITIVE HR ADVISORY • المستشار الذكي للموارد البشرية',
      'sentiment_report': 'Team Sentiment Report',
      'advisory_memo': 'ADVISORY MEMO',
      'generating_analysis': 'GENERATING ANALYSIS...',
      'generate_analysis': 'GENERATE ANALYSIS',
      'acknowledge': 'ACKNOWLEDGE',
      'office_presence': 'OFFICE PRESENCE',
      'signal_intensity': 'Signal Intensity',
      'velocity_forecast': 'Velocity Forecast',
      'velocity_desc': 'Target completion pacing is perfectly green. No bottlenecks.',
      'overall_productivity': 'Overall productivity is up 12% this week.',
      'view_analysis': 'VIEW ANALYSIS',
      'logged_hours_pacing': 'LOGGED HOURS',
      'time_matrix_label': 'TIME MATRIX',

      // Requests View
      'requests_subtitle': 'HR SERVICE CENTER • مركز الخدمات الإلكترونية',
      'requests_title': 'Requests Matrix • البوابة',
      'submit_new_request': 'SUBMIT NEW REQUEST • تقديم طلب جديد',
      'request_type_leave': 'Leave',
      'request_type_loan': 'Loan',
      'request_type_deputation': 'Deput.',
      'request_type_overtime': 'Overt.',
      'request_type_salary': 'Cert.',
      'leave_type': 'Leave Type',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'loan_amount': 'Loan Amount (SAR)',
      'repayment_months': 'Repayment Months',
      'destination_office': 'Destination Office',
      'deputation_purpose': 'Deputation Purpose',
      'overtime_date': 'Overtime Date',
      'hours_requested': 'Hours Requested',
      'cert_notes': 'Certificate Recipient / Notes',
      'submit_request': 'SUBMIT REQUEST • إرسال الطلب',
      'submitted_success': 'SUBMITTED SUCCESSFULLY • تم الإرسال',
      'requests_history': 'REQUESTS HISTORY LEDGER • سجل تاريخ الطلبات',
      'audit_ledger': 'Audit ledger',
      'no_requests': 'No requests submitted yet.',

      // Attendance View
      'attendance_calendar_subtitle': 'BIOMETRIC SECURITY CALENDAR • تقويم التحضير',
      'attendance_calendar_title': 'Attendance Calendar • الحضور',
      'punch': 'PUNCH',
      'punch_log': 'Punch Log • تفاصيل اليوم',
      'clock_in': 'Clock In • حضور',
      'clock_out': 'Clock Out • انصراف',
      'attendance_days': 'Attendance Days',
      'biometric_accuracy': 'Biometric Accuracy',
      'secure_100': '100% Secure',
      'add_punch_entry': 'Add Punch Entry • تسجيل يدوي',
      'submit_punch': 'SUBMIT PUNCH • حفظ التسجيل',

      // Reports View
      'reports_subtitle': 'ANALYTICAL REPORTING • التقارير والإحصائيات',
      'reports_title': 'Security Attendance Report',
      'weekly_pacing': 'WEEKLY PACING MATRIX • وتيرة الإنتاجية',
      'presence_highlights': 'PRESENCE HIGHLIGHTS • خلاصة الحضور',
      'active_attendance': 'Active attendance',
      'average_daily': 'Average Daily',
      'early_arrivals': 'Early Arrivals',
      'security_core': 'Security Core',
      'receipt': 'RECEIPT',

      // Profile View
      'profile_subtitle': 'SYSTEM IDENTITY PANEL • إدارة الملف الشخصي',
      'profile_title': 'Profile & Diagnostics',
      'identity_settings': 'IDENTITY SETTINGS CONFIGURATION',
      'full_name': 'Full Name Matrix',
      'assigned_role': 'Assigned Title / Role',
      'weekly_goal': 'Weekly Goal Capacity (Hours)',
      'telemetry_status': 'Default Telemetry Status',
      'bg_mode': 'App Background Mode / وضع الخلفية',
      'light_glow': 'LIGHT GLOW • مظهر مضيء',
      'dark_mesh': 'DARK MESH • مظهر مظلم',
      'lang_selector': 'Language Selector / لغة الواجهة',
      'commit_changes': 'COMMIT CHANGES • حفظ التعديلات',
       'security_diagnostics': 'SECURITY DIAGNOSTICS • معايير الأمان',
      // Onboarding / Login
      'get_started': 'GET STARTED',
      'enter_subdomain': 'Enter Subdomain',
      'subdomain_hint': 'company.crystalhr.com',
      'email': 'Email Address',
      'password': 'Password',
      'signin': 'SIGN IN',
      'next': 'NEXT',
      'back': 'BACK',
      'welcome_desc': 'The premium fintech workspace for modern presence, smart metrics, and predictive HR management.',
      'invalid_domain': 'Please enter a valid subdomain',
      'invalid_credentials': 'Enter a valid email and password (min 6 chars)',
    },
    'ar': {
      // Common
      'status': 'الحالة',
      'active': 'نشط',
      'remote': 'عن بعد',
      'out': 'خارج المكتب',
      'method': 'طريقة التحضير: ',
      'fingerprint': 'بصمة الإصبع',
      'nfc': 'باقة NFC الرقمية',
      'manual_override': 'تجاوز إداري',
      'logs': 'السجلات',
      'date': 'التاريخ',
      'time': 'الوقت',
      'type': 'النوع',
      'notes': 'ملاحظات وتفاصيل إضافية',
      'submit': 'إرسال',

      // Dashboard
      'welcome_back': 'مرحباً بك،',
      'current_session': 'تفاصيل الجلسة الحالية',
      'time_matrix': 'مصفوفة الوقت',
      'weekly_pacing_desc': 'الإنتاجية الأسبوعية',
      'logged_hours': 'ساعات العمل المسجلة',
      'shift_ends_in': 'ينتهي الدوام خلال',
      'session_standby': 'النظام في وضع الاستعداد حالياً',
      'weekly_goal_pacing': 'معدل الإنتاجية الأسبوعي المستهدف',
      'target': 'المستهدف:',
      'completed': 'المنجز فعلياً:',
      'pacing': 'الوتيرة',
      'weekly_presence': 'مؤشرات الحضور والانصراف الأسبوعي',
      'pacing_indicators': 'مؤشرات الحضور الأسبوعي',
      'next_engagements': 'الارتباطات والاجتماعات القادمة',
      'agenda_details': 'جدول الأعمال ورموز المزامنة',
      'add_event': 'إضافة حدث جديد',
      'hr_advisory': 'المستشار الذكي للموارد البشرية (ذكاء اصطناعي)',
      'sentiment_report': 'تقرير الروح المعنوية والملاحظات لفريق العمل',
      'advisory_memo': 'توصيات المستشار الذكي',
      'generating_analysis': 'جاري تحليل البيانات وتوليد التوصيات...',
      'generate_analysis': 'توليد التحليل الفوري',
      'acknowledge': 'فهمت وتأكيد القراءة',
      'office_presence': 'التواجد في المكتب',
      'signal_intensity': 'مؤشر الكثافة والنشاط',
      'velocity_forecast': 'توقعات سرعة الإنجاز',
      'velocity_desc': 'معدل إنجاز الأهداف ممتاز ولا توجد أي معوقات حالية.',
      'overall_productivity': 'معدل الإنتاجية الكلي ارتفع بنسبة 12% هذا الأسبوع.',
      'view_analysis': 'عرض التحليل الذكي',
      'logged_hours_pacing': 'ساعات العمل المسجلة',
      'time_matrix_label': 'مصفوفة الوقت',

      // Requests View
      'requests_subtitle': 'مركز الخدمات الذاتية للموظفين',
      'requests_title': 'بوابة تقديم ومتابعة الطلبات',
      'submit_new_request': 'تقديم طلب إلكتروني جديد',
      'request_type_leave': 'إجازة',
      'request_type_loan': 'سلفة',
      'request_type_deputation': 'انتداب',
      'request_type_overtime': 'إضافي',
      'request_type_salary': 'تعريف',
      'leave_type': 'نوع الإجازة المطلوبة',
      'start_date': 'تاريخ بدء الطلب',
      'end_date': 'تاريخ انتهاء الطلب',
      'loan_amount': 'مبلغ السلفة المطلوبة (بالريال السعودي)',
      'repayment_months': 'مدة السداد بالأشهر',
      'destination_office': 'مكتب أو مدينة وجهة الانتداب',
      'deputation_purpose': 'الهدف والغرض من الانتداب',
      'overtime_date': 'تاريخ يوم العمل الإضافي',
      'hours_requested': 'عدد الساعات المطلوبة',
      'cert_notes': 'الجهة الموجه إليها خطاب التعريف / ملاحظات',
      'submit_request': 'إرسال الطلب للاعتماد',
      'submitted_success': 'تم إرسال طلبك بنجاح',
      'requests_history': 'سجل الطلبات والعمليات التاريخية للموظف',
      'audit_ledger': 'سجل المراجعة والتدقيق الموثق',
      'no_requests': 'لا يوجد طلبات مسجلة حالياً.',

      // Attendance View
      'attendance_calendar_subtitle': 'تقويم ومطابقة الحضور والانصراف البيومتري الموثق',
      'attendance_calendar_title': 'سجل التحضير الشهري',
      'punch': 'تحضير يدوي',
      'punch_log': 'تفاصيل اليوم والعمليات المسجلة',
      'clock_in': 'تسجيل الحضور',
      'clock_out': 'تسجيل الانصراف',
      'attendance_days': 'أيام الحضور الفعلية',
      'biometric_accuracy': 'دقة المطابقة البيومترية',
      'secure_100': 'آمن ومحمي بالكامل 100%',
      'add_punch_entry': 'تسجيل حركة حضور/انصراف يدوية',
      'submit_punch': 'حفظ الحركة وتحديث السجل',

      // Reports View
      'reports_subtitle': 'بوابة التقارير التحليلية والبيانات الموثقة',
      'reports_title': 'لوحة إحصائيات الحضور والإنتاجية',
      'weekly_pacing': 'مصفوفة الإنتاجية الأسبوعية والمقارنة',
      'presence_highlights': 'خلاصة حضور وانصراف الموظف',
      'active_attendance': 'أيام الحضور النشط',
      'average_daily': 'معدل ساعات العمل اليومي',
      'early_arrivals': 'نسبة الوصول المبكر للمكتب',
      'security_core': 'نظام التحقق والتوثيق المعتمد',
      'receipt': 'سند التحضير',

      // Profile View
      'profile_subtitle': 'لوحة التحكم وإدارة هوية الموظف',
      'profile_title': 'الملف الشخصي والتشخيصات الأمنية',
      'identity_settings': 'تعديل وإعدادات الهوية الرقمية للموظف',
      'full_name': 'الاسم الكامل الموثق',
      'assigned_role': 'المسمى الوظيفي والمسؤوليات',
      'weekly_goal': 'الساعات الأسبوعية المطلوبة',
      'telemetry_status': 'حالة العمل الافتراضية للجهاز',
      'bg_mode': 'وضع مظهر خلفية التطبيق',
      'light_glow': 'مظهر مضيء وناعم',
      'dark_mesh': 'مظهر مظلم كلاسيكي فخم',
      'lang_selector': 'لغة واجهة المستخدم والتطبيق',
      'commit_changes': 'حفظ التعديلات وتحديث البيانات',
      'security_diagnostics': 'التدقيق والتشخيص الأمني للنظام',
      // Onboarding / Login
      'get_started': 'ابدأ الآن',
      'enter_subdomain': 'أدخل النطاق الفرعي للمنشأة',
      'subdomain_hint': 'company.crystalhr.com',
      'email': 'البريد الإلكتروني الموثق',
      'password': 'كلمة المرور',
      'signin': 'تسجيل الدخول الآمن',
      'next': 'التالي',
      'back': 'رجوع',
      'welcome_desc': 'منصة الموارد البشرية الذكية والمصممة لتسهيل إدارة حضورك، وإنتاجيتك، ومستشارك الشخصي الفوري.',
      'invalid_domain': 'يرجى إدخال نطاق فرعي صحيح للمنشأة',
      'invalid_credentials': 'يرجى إدخال بريد إلكتروني صحيح وكلمة مرور (6 خانات كحد أدنى)',
    }
  };

  static String translate(String key, String lang) {
    final language = _localizedValues.containsKey(lang) ? lang : 'ar';
    return _localizedValues[language]?[key] ?? key;
  }
}
