USE beattend_staging_db;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NOT NULL DEFAULT 'tenant-sol-102';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS name_en VARCHAR(255) NULL AFTER name_ar;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255) NULL AFTER name_en;
